const $ = (id) => document.getElementById(id);
const STORE = 'mick-g-career-v2';
const ranks = [{name:'UNKNOWN', at:0},{name:'RUNNER',at:100},{name:'FIXER',at:250},{name:'OPERATOR',at:500},{name:'SHOT-CALLER',at:900},{name:'CITY LEGEND',at:1500}];
const defaultState = {cash:1250, notoriety:0, heat:8, crew:2, maxCrew:5, time:22, day:1, rangeLevel:1, ammo:6, maxAmmo:6, score:0, streak:0, best:0, shots:0, hits:0, jobs:[], achievements:[], history:['Career opened. The city is listening.'], tutorial:0};
let state = {...defaultState, ...(JSON.parse(localStorage.getItem(STORE)||'null')||{})};
const lessons = [['Start with a low-risk run','Jobs have windows, requirements and consequences. Read the brief, assign the right crew, then let the clock do its work.'],['Watch your heat','Heat rises when moves get loud. Lay low, train, or choose a clean social job before pushing again.'],['Build a real crew','Crew members are a limited resource. A person on a job is unavailable until the operation resolves.'],['Notoriety is earned','Cash keeps the lights on; notoriety unlocks better routes, safer options and new achievements.']];
const jobs = [
 {id:'delivery',title:'The Quiet Delivery',type:'CLEAN',brief:'Move a sealed case across town before the last bus.',window:[20,2],need:1,reward:340,rep:32,heat:4,duration:2,desc:'Low profile. Reliable money. A good first move.'},
 {id:'club',title:'Club Door Introduction',type:'SOCIAL',brief:'Put the right name on the guest list and turn a rival room into an ally.',window:[21,1],need:1,reward:260,rep:45,heat:2,duration:3,desc:'No confrontation required. Timing and charm do the work.'},
 {id:'range',title:'Range Qualification',type:'TRAINING',brief:'Beat the house score in a controlled fictional training drill.',window:[0,23],need:1,reward:180,rep:20,heat:-5,duration:1,desc:'Improve your aim and cool the city down.'},
 {id:'intel',title:'The Long Conversation',type:'INTEL',brief:'Meet an informant at the café and verify a rumour before dawn.',window:[22,4],need:1,reward:520,rep:75,heat:8,duration:4,desc:'A careful operator gathers facts before choosing a route.'},
 {id:'front',title:'Front Business Audit',type:'BUSINESS',brief:'Find the leak in a fictional storefront ledger without making noise.',window:[8,18],need:2,reward:760,rep:105,heat:12,duration:5,desc:'Requires two crew. Big upside, but a failed audit closes the shop.'}
];
function save(){localStorage.setItem(STORE,JSON.stringify(state)); render();}
function money(n){return '€'+Math.max(0,Math.round(n)).toLocaleString('en-IE');}
function clock(){return `${String(state.time).padStart(2,'0')}:00`}
function rankInfo(){let r=ranks[0]; ranks.forEach(x=>{if(state.notoriety>=x.at)r=x}); return r}
function nextRank(){return ranks.find(x=>x.at>state.notoriety)||ranks.at(-1)}
function windowOpen(j){return j.window[0]<=j.window[1]?state.time>=j.window[0]&&state.time<=j.window[1]:state.time>=j.window[0]||state.time<=j.window[1]}
function addHistory(text){state.history.unshift(`${clock()} · ${text}`);state.history=state.history.slice(0,8)}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2600)}
function advance(hours){state.time=(state.time+hours)%24;if(state.time<hours)state.day++; state.crew=Math.min(state.maxCrew,state.crew+Math.floor(hours/4));}
function render(){
 const r=rankInfo(), n=nextRank(); $('clock').textContent=clock();$('cash').textContent=money(state.cash);$('notoriety').textContent=state.notoriety;$('crew').textContent=`${state.crew}/${state.maxCrew}`;$('crewText').textContent=`${state.crew} available`;$('heat').textContent=state.heat;$('heatLabel').textContent=state.heat<25?'LOW HEAT':state.heat<60?'WATCHED':'HOT';$('heatDot').className='heat-dot '+(state.heat<25?'cool':state.heat<60?'warm':'hot');$('rank').textContent=ranks.indexOf(r)+1;$('rankName').textContent=r.name;$('nextRank').textContent=n.at;$('rankProgressName').textContent=n.name;$('rankProgress').textContent=`${state.notoriety} / ${n.at}`;$('progressBar').style.width=`${Math.min(100,state.notoriety/n.at*100)}%`;$('rankHint').textContent=state.heat>=80?'The city is too hot. Lay low before taking another risk.':'Complete clean jobs and train to earn notoriety.';
 $('rangeLevel').textContent=`LEVEL ${state.rangeLevel}`;$('ammoLabel').textContent=`AMMO ${state.ammo}/${state.maxAmmo}`;$('rangeScore').textContent=state.score;$('rangeStreak').textContent=state.streak;$('rangeBest').textContent=state.best;$('accuracyLabel').textContent=`ACCURACY ${state.shots?Math.round(state.hits/state.shots*100):0}%`;$('roundLabel').textContent=`ROUND ${Math.min(5,Math.floor(state.shots/5)+1)} / 5`;
 renderStreet();renderJobs();renderAchievements();$('history').innerHTML=state.history.map(x=>`<li>${x}</li>`).join('');
}
function renderStreet(){let active=jobs.filter(j=>windowOpen(j)&&!state.jobs.includes(j.id));$('jobBadge').textContent=active.length; $('cityMood').textContent=state.heat>60?'EYES EVERYWHERE':state.time>=20||state.time<5?'QUIET NIGHT':'DAY SHIFT';$('streetCards').innerHTML=active.slice(0,3).map(j=>card(j)).join('')||`<div class="panel empty"><h2>No easy openings</h2><p>Advance time by taking training or check the operations board for the next window.</p><button class="button secondary" data-view="jobs">View board</button></div>`; bindJobButtons()}
function card(j){return `<article class="job-card ${j.type.toLowerCase()}"><div class="job-top"><span class="job-type">${j.type}</span><span class="job-time">${j.window[0]}:00—${j.window[1]}:00</span></div><h3>${j.title}</h3><p>${j.brief}</p><div class="job-meta"><span>＋${money(j.reward)}</span><span>✦ +${j.rep}</span><span>⌁ ${j.heat>0?'+':''}${j.heat} heat</span></div><button class="button" data-job="${j.id}">Assign crew <span>→</span></button></article>`}
function renderJobs(){$('jobList').innerHTML=jobs.map(j=>`<article class="job-row ${state.jobs.includes(j.id)?'complete':''}"><div class="job-icon">${j.type[0]}</div><div class="job-copy"><div><span class="job-type">${j.type}</span>${windowOpen(j)?'<span class="open">OPEN NOW</span>':'<span class="closed">WINDOW CLOSED</span>'}</div><h3>${j.title}</h3><p>${j.desc}</p><small>Needs ${j.need} crew · ${j.duration}h · ${money(j.reward)} +${j.rep} rep</small></div><button class="button ${windowOpen(j)&&!state.jobs.includes(j.id)?'':'secondary'}" data-job="${j.id}" ${state.jobs.includes(j.id)?'disabled':''}>${state.jobs.includes(j.id)?'DONE':windowOpen(j)?'RUN':'LOCKED'}</button></article>`).join('');bindJobButtons()}
function bindJobButtons(){document.querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>runJob(b.dataset.job));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view))}
function runJob(id){let j=jobs.find(x=>x.id===id);if(!j||state.jobs.includes(id))return;if(!windowOpen(j)){toast('That opportunity is outside its time window.');return}if(state.crew<j.need){toast(`You need ${j.need} available crew.`);return}if(state.heat>=80&&j.heat>0){toast('Too much heat. Lay low or train first.');return}state.crew-=j.need;advance(j.duration);state.cash+=j.reward;state.notoriety+=j.rep;state.heat=Math.max(0,Math.min(100,state.heat+j.heat));state.jobs.push(id);addHistory(`${j.title} completed: ${money(j.reward)} and +${j.rep} notoriety.`);checkAchievements();toast(`${j.title} complete — the city noticed.`);save()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'})}
function fire(){if(state.ammo<=0){toast('Empty chamber. Reload before training.');return}state.ammo--;state.shots++;let target=$('target'), hit=Math.random()<(0.58+state.rangeLevel*.07);target.style.left=`${20+Math.random()*60}%`;target.style.top=`${25+Math.random()*55}%`;if(hit){state.hits++;state.streak++;let points=10+state.streak*2+state.rangeLevel*3;state.score+=points;state.best=Math.max(state.best,state.score);state.cash+=20;state.notoriety+=5;$('hitMarker').textContent=`+${points}`;$('hitMarker').classList.remove('pop');void $('hitMarker').offsetWidth;$('hitMarker').classList.add('pop');addHistory(`Range hit: +${points} score, +5 notoriety.`)}else{state.streak=0;toast('Miss. Slow down and read the target.')}checkAchievements();save()}
function reload(){let missing=state.maxAmmo-state.ammo;if(!missing){toast('Already loaded.');return}state.ammo=state.maxAmmo;advance(1);toast('Reloaded. One hour passes.');save()}
function upgrade(){let cost=state.rangeLevel*500;if(state.cash<cost){toast(`You need ${money(cost)} for the next kit upgrade.`);return}state.cash-=cost;state.rangeLevel++;state.maxAmmo++;state.ammo=state.maxAmmo;addHistory(`Range upgraded to level ${state.rangeLevel}.`);toast('Range kit upgraded.');save()}
function checkAchievements(){let tests=[['first','First Move',state.jobs.length>=1,'Complete your first operation.'],['earner','Clean Money',state.cash>=2500,'Hold €2,500.'],['noticed','Name on the Wall',state.notoriety>=100,'Reach 100 notoriety.'],['marksman','Steady Hands',state.hits>=10,'Land ten range hits.'],['hotshot','No Panic',state.streak>=5,'Build a five-hit streak.'],['operator','Operator',state.jobs.length>=3,'Complete three different operations.']];tests.forEach(([id,name,ok,desc])=>{if(ok&&!state.achievements.includes(id)){state.achievements.push(id);state.notoriety+=15;addHistory(`Achievement unlocked: ${name} (+15 notoriety).`);toast(`Achievement unlocked: ${name}`)}})}
function renderAchievements(){let tests=[['first','First Move','Complete your first operation.',state.achievements.includes('first')],['earner','Clean Money','Hold €2,500.',state.achievements.includes('earner')],['noticed','Name on the Wall','Reach 100 notoriety.',state.achievements.includes('noticed')],['marksman','Steady Hands','Land ten range hits.',state.achievements.includes('marksman')],['hotshot','No Panic','Build a five-hit streak.',state.achievements.includes('hotshot')],['operator','Operator','Complete three different operations.',state.achievements.includes('operator')]];$('achievements').innerHTML=tests.map(x=>`<div class="achievement ${x[3]?'unlocked':''}"><span>${x[3]?'✓':'○'}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')}
$('fireButton').onclick=fire;$('reloadButton').onclick=reload;$('upgradeRange').onclick=upgrade;$('tutorialNext').onclick=()=>{state.tutorial=(state.tutorial+1)%lessons.length;$('tutorialTitle').textContent=lessons[state.tutorial][0];$('tutorialText').textContent=lessons[state.tutorial][1]};$('resetGame').onclick=()=>{if(confirm('Reset this fictional career?')){state={...defaultState};save();toast('Career reset.')}};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.view));setInterval(()=>{if(document.visibilityState==='visible'){$('clock').textContent=clock()}},1000);render();
